--- #YAML:1.0
name:                Language-MuldisD
version:             0.13.0
abstract:            Formal spec of Muldis D relational DBMS lang
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Darren Duncan <perl@DarrenDuncan.net>
